[tools]
pre-commit = "4.5"
python = "3.13"
ruff = "0.14.13"
uv = "0.9"

[settings]
experimental = true
python.uv_venv_auto = true

[env]
OLLAMA_BASE_URL="http://host.docker.internal:11434"
LLM_BASE_URL="http://localhost:4000"
LLM_PROVIDER="openai"
VECTORDB_K="10"
RAGAS_DO_NOT_TRACK="true"
LLM_TEMPERATURE="0.1"

[hooks]
enter = "bash ./scripts/setup_project"

[tasks.docker-build]
description = "Build Docker images"
run = "bash ./scripts/build_docker_images"

[tasks.mealierag-tests]
description = "Run tests"
run = "cd src/mealierag && uv run pytest --cov=mealierag"
