model_list:
  - model_name: mealie-rag-llm
    litellm_params:
      model: ollama/llama3.1:8b
      api_base: os.environ/OLLAMA_BASE_URL
      api_key: ""
      num_ctx: 8192
  - model_name: mealie-rag-embedding
    litellm_params:
      model: ollama/bge-m3
      api_base: os.environ/OLLAMA_BASE_URL
      api_key: ""
  - model_name: helios-llama3.1
    litellm_params:
      model: ollama/llama3.1:8b
      api_base: os.environ/OLLAMA_HELIOS_BASE_URL
      api_key: ""
      num_ctx: 8192
  - model_name: helios-mistral
    litellm_params:
      model: ollama/mistral:instruct
      api_base: os.environ/OLLAMA_HELIOS_BASE_URL
      api_key: ""
      num_ctx: 8192
  - model_name: helios-qwen2.5
    litellm_params:
      model: ollama/qwen2.5:7b
      api_base: os.environ/OLLAMA_HELIOS_BASE_URL
      api_key: ""
      num_ctx: 8192
  - model_name: helios-gemma3
    litellm_params:
      model: ollama/gemma3:12b
      api_base: os.environ/OLLAMA_HELIOS_BASE_URL
      api_key: ""
      num_ctx: 8192
  - model_name: helios-bge-m3
    litellm_params:
      model: ollama/bge-m3
      api_base: os.environ/OLLAMA_HELIOS_BASE_URL
      api_key: ""
litellm_settings:
  success_callback: ["langfuse"]
