model_list:
  - model_name: mealie-rag-llm
    litellm_params:
      model: ollama/llama3.1:8b
      api_base: os.environ/OLLAMA_BASE_URL
      api_key: ""
      num_ctx: 8192
  - model_name: mealie-rag-embedding
    litellm_params:
      model: ollama/bge-m3
      api_base: os.environ/OLLAMA_BASE_URL
      api_key: ""
litellm_settings:
  success_callback: ["langfuse"]
