model_list:
  - model_name: llama3.1:8b
    litellm_params:
      model: ollama/llama3.1:8b
      api_base: os.environ/OLLAMA_BASE_URL
      api_key: ""
  - model_name: bge-m3
    litellm_params:
      model: ollama/bge-m3
      api_base: os.environ/OLLAMA_BASE_URL
      api_key: ""
litellm_settings:
  success_callback: ["langfuse"]
